//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electricity
{


    public partial class pay
    {

        /// <summary>
        /// FormPay control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm FormPay;

        /// <summary>
        /// GridBills control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridBills;

        /// <summary>
        /// LblSelected control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblSelected;

        /// <summary>
        /// BtnPaySelected control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnPaySelected;

        /// <summary>
        /// BtnBackBills control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnBackBills;

        /// <summary>
        /// LblMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblMsg;
    }
}
